# Generated by Django 3.0.7 on 2020-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
